apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: ingress-nginx
spec:
  interval: 10m
  chart:
    chart: ingress-nginx
    version: 4.11.2
    sourceRef:
      kind: HelmRepository
      name: ingress-nginx
      namespace: ingress-nginx
  values:
    controller:
      service:
        type: LoadBalancer
      metrics:
        enabled: true
