apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: gitea-postgresql
  namespace: postgresql
spec:
  interval: 10m
  chart:
    spec:
      chart: ./clusters/production/charts/postgresql-16.7.27.tgz
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    auth:
      existingSecret: gitea-postgresql
    primary:
      persistence:
        enabled: true
        size: 10Gi
