apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: gitea-postgresql
  namespace: postgresql
spec:
  interval: 10m
  chart:
    spec:
      chart: postgresql
      version: 16.7.27
      sourceRef:
        kind: HelmChart
        name: postgresql-direct
        namespace: flux-system
  values:
    image:
      tag: 17.6.0
    auth:
      existingSecret: gitea-postgresql
    primary:
      persistence:
        enabled: true
        size: 10Gi
