apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  releaseName: gitea
  interval: 10m
  chart:
    spec:
      chart: gitea
      version: 10.3.0
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: flux-system
  values:
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: git.beane.me
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: gitea-tls
          hosts:
            - git.beane.me
    postgresql:
      enabled: false
    gitea:
      database:
        host: postgresql.default.svc.cluster.local
        existingSecret: gitea-postgresql
      admin:
        existingSecret: gitea-admin
    persistence:
      enabled: true
      size: 10Gi
